<a href="https://colab.research.google.com/github/nikhilgowda736/12feb/blob/main/Data_class_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing Packeges 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [2]:
#Importing dataset
dataset = pd.read_csv('/content/Data.csv')

In [3]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [5]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [6]:
from re import X
#Independent and Depemdent Variables 
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values

In [7]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
#Handling Missing Data 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
x[:,1:3] = imputer.fit_transform(x[:,1:3])

In [10]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [11]:
#Encoding Categorical Data 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [13]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [14]:
#Encoding Categorical Data - Depender Variable 
from sklearn.preprocessing import LabelEncoder
label_y = LabelEncoder()
y=label_y.fit_transform(y)

In [15]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [16]:
 #splitting the dataset into the training set test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=125)

In [17]:
x_train

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0]], dtype=object)

In [18]:
x_test

array([[1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [19]:
y_train

array([0, 0, 1, 1, 0, 0, 1, 0])

In [20]:
y_test

array([1, 1])

In [21]:
# Featuer Scaling 
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [22]:
x_train

array([[ 1.29099445, -0.77459667, -0.57735027,  0.5678988 ,  0.61885324],
       [-0.77459667, -0.77459667,  1.73205081, -0.27277029, -1.24158238],
       [-0.77459667,  1.29099445, -0.57735027, -0.07601795, -0.14599252],
       [ 1.29099445, -0.77459667, -0.57735027, -0.88091389, -0.68345169],
       [-0.77459667, -0.77459667,  1.73205081, -0.39797633, -0.40438635],
       [-0.77459667,  1.29099445, -0.57735027,  1.53377393,  1.64209282],
       [ 1.29099445, -0.77459667, -0.57735027,  1.21181555,  1.2700057 ],
       [-0.77459667,  1.29099445, -0.57735027, -1.68580983, -1.05553882]])

In [23]:
x_test

array([[ 1.29099445, -0.77459667, -0.57735027, -0.55895551,  0.15374433],
       [-0.77459667, -0.77459667,  1.73205081, -2.16874739, -1.6136695 ]])

In [24]:
#Applying a ML Model 

In [25]:
#Data Visualisation